apiVersion: v1
kind: Pod
metadata:
  name: openssh-server
spec:
  containers:
  - name: openssh-server
    image: linuxserver/openssh-server:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 2222
    env:
    - name: PASSWORD_ACCESS
      value: "true"
    - name: USER_PASSWORD
      value: "password123"
    - name: USER_NAME
      value: "sshuser"
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.2"
        memory: "256Mi"
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: false
