apiVersion: v1
kind: Service
metadata:
  name: bank-app-service
spec:
  selector:
    app: bank-app
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cdn-service
spec:
  selector:
    app: cdn
  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: social-app-service
spec:
  selector:
    app: social-app
  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dns-service
spec:
  # type: NodePort
  # selector:
  #   app: dns-server
  selector:
    app: dns-server
  ports:
  - port: 53
    name: dns-udp
    targetPort: 30053
    protocol: UDP
  - port: 53
    name: dns-tcp
    targetPort: 30053
    protocol: TCP
