name: Build and Push Bank app Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'bank_app/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bank_app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ${{ github.workspace }}/bank_app/Dockerfile
          context: ${{ github.workspace }}/bank_app
          push: true
          tags: "ghcr.io/team-aaaaaaaaaaaaaaaa/bank_app:latest"