name: Build and Push CDN Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'cdn/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cdn

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ${{ github.workspace }}/cdn/Dockerfile
          context: ${{ github.workspace }}/cdn
          push: true
          tags: "ghcr.io/team-aaaaaaaaaaaaaaaa/cdn:latest"